// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7kHHtmp7kw7v5e6mQsr6wa
// Component: aYyZ3CnFHM

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { CmsRowImage } from "@plasmicpkgs/plasmic-cms";
import { CmsRowField } from "@plasmicpkgs/plasmic-cms";

import { useScreenVariants as useScreenVariantsqd2M7Fh1C7FCr } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qd2M7fh1c7fCR/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_martas_radical_website.module.css"; // plasmic-import: 7kHHtmp7kw7v5e6mQsr6wa/projectcss
import sty from "./PlasmicExhibitionCardSmall.module.css"; // plasmic-import: aYyZ3CnFHM/css

import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: TE7eTcYpH1C/icon

createPlasmicElementProxy;

export type PlasmicExhibitionCardSmall__VariantMembers = {};
export type PlasmicExhibitionCardSmall__VariantsArgs = {};
type VariantPropType = keyof PlasmicExhibitionCardSmall__VariantsArgs;
export const PlasmicExhibitionCardSmall__VariantProps =
  new Array<VariantPropType>();

export type PlasmicExhibitionCardSmall__ArgsType = {};
type ArgPropType = keyof PlasmicExhibitionCardSmall__ArgsType;
export const PlasmicExhibitionCardSmall__ArgProps = new Array<ArgPropType>();

export type PlasmicExhibitionCardSmall__OverridesType = {
  root?: Flex__<"a"> & Partial<LinkProps>;
  cmsEntryImage?: Flex__<typeof CmsRowImage>;
  img?: Flex__<typeof PlasmicImg__>;
  freeBox?: Flex__<"div">;
  p?: Flex__<"p">;
  svg?: Flex__<"svg">;
};

export interface DefaultExhibitionCardSmallProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicExhibitionCardSmall__RenderFunc(props: {
  variants: PlasmicExhibitionCardSmall__VariantsArgs;
  args: PlasmicExhibitionCardSmall__ArgsType;
  overrides: PlasmicExhibitionCardSmall__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqd2M7Fh1C7FCr()
  });

  return (
    <PlasmicLink__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      component={Link}
      href={"martaespiridiao.com/error-417-expectation-failed"}
      platform={"nextjs"}
    >
      <CmsRowImage
        data-plasmic-name={"cmsEntryImage"}
        data-plasmic-override={overrides.cmsEntryImage}
        className={classNames("__wab_instance", sty.cmsEntryImage)}
        srcProp={"src"}
      >
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={
            hasVariant(globalVariants, "screen", "tablet") ? "15vh" : "20vh"
          }
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"auto"}
          src={"https://studio.plasmic.app/static/img/placeholder-full.png"}
        />
      </CmsRowImage>
      <CmsRowField
        className={classNames("__wab_instance", sty.cmsEntryField__xhShm)}
        themeResetClassName={classNames(
          projectcss.root_reset,
          projectcss.root_reset_tags,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens
        )}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <CmsRowField
          className={classNames("__wab_instance", sty.cmsEntryField___6Zvm2)}
          dateFormat={"MMMM D, YYYY"}
          field={"expoDataStart"}
          themeResetClassName={classNames(
            projectcss.root_reset,
            projectcss.root_reset_tags,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens
          )}
        />

        <p
          data-plasmic-name={"p"}
          data-plasmic-override={overrides.p}
          className={classNames(
            projectcss.all,
            projectcss.p,
            projectcss.__wab_text,
            sty.p
          )}
        >
          {"\u2014"}
        </p>
        <CmsRowField
          className={classNames("__wab_instance", sty.cmsEntryField__cqhVo)}
          dateFormat={"MMMM D, YYYY"}
          field={"expoDataEnd"}
          themeResetClassName={classNames(
            projectcss.root_reset,
            projectcss.root_reset_tags,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens
          )}
        />
      </div>
      <CmsRowField
        className={classNames("__wab_instance", sty.cmsEntryField__iGuOm)}
        dateFormat={"MMMM D, YYYY"}
        field={"expoLocal"}
        themeResetClassName={classNames(
          projectcss.root_reset,
          projectcss.root_reset_tags,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens
        )}
      />

      <Icon38Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />
    </PlasmicLink__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "cmsEntryImage", "img", "freeBox", "p", "svg"],
  cmsEntryImage: ["cmsEntryImage", "img"],
  img: ["img"],
  freeBox: ["freeBox", "p"],
  p: ["p"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "a";
  cmsEntryImage: typeof CmsRowImage;
  img: typeof PlasmicImg__;
  freeBox: "div";
  p: "p";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicExhibitionCardSmall__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicExhibitionCardSmall__VariantsArgs;
    args?: PlasmicExhibitionCardSmall__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicExhibitionCardSmall__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicExhibitionCardSmall__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicExhibitionCardSmall__ArgProps,
          internalVariantPropNames: PlasmicExhibitionCardSmall__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicExhibitionCardSmall__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicExhibitionCardSmall";
  } else {
    func.displayName = `PlasmicExhibitionCardSmall.${nodeName}`;
  }
  return func;
}

export const PlasmicExhibitionCardSmall = Object.assign(
  // Top-level PlasmicExhibitionCardSmall renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cmsEntryImage: makeNodeComponent("cmsEntryImage"),
    img: makeNodeComponent("img"),
    freeBox: makeNodeComponent("freeBox"),
    p: makeNodeComponent("p"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicExhibitionCardSmall
    internalVariantProps: PlasmicExhibitionCardSmall__VariantProps,
    internalArgProps: PlasmicExhibitionCardSmall__ArgProps
  }
);

export default PlasmicExhibitionCardSmall;
/* prettier-ignore-end */
